name: Build and Test ProvSQL

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
  workflow_dispatch:
    paths-ignore:
      - 'doc/**'

jobs:
  test:
    strategy:
      matrix:
        pg: [9.5, 9.6, 10, 11, 12, 13, 14]
    name: 🐘 PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - run: pg-start ${{ matrix.pg }} libgraph-easy-perl libboost-dev unzip zlib1g-dev libgmp-dev
      - run: pg_dropcluster ${{ matrix.pg }} main
      - run: "curl 'http://reasoning.cs.ucla.edu/c2d/fetchme.php' -H 'Content-Type: application/x-www-form-urlencoded' --data 'os=Linux+i386&type=&s=&n=Pierre+Senellart&e=pierre%40senellart.com&o=ENS' -o c2d && unzip c2d && mv c2d_linux /usr/local/bin/c2d && chmod a+x /usr/local/bin/c2d"
      - run: git clone https://github.com/crillab/d4.git && cd d4 && make && mv d4 /usr/local/bin && cd ..
      - run: git clone https://github.com/QuMuLab/dsharp.git && cd dsharp && mv Makefile_gmp Makefile && make && mv dsharp /usr/local/bin && cd ..
      - run: git clone https://bitbucket.org/kuldeepmeel/weightmc/src/master/ weightmc && cd weightmc/wmc-src && ./configure && make && mv weightmc /usr/local/bin && cd ../..
      - uses: actions/checkout@v2
      - run: make && make tdkc && make install
      - run: echo "shared_preload_libraries = 'provsql'" >> /etc/postgresql/${{ matrix.pg }}/test/postgresql.conf
      - run: service postgresql restart
      - run: make installcheck PGUSER=postgres || bash -c "shopt -s nullglob; cat /tmp/tmp.provsql*/regression.diffs && for i in /tmp/provsql*; do echo $i && cat $i; done; false"

  docker:
    needs: test
    if: github.ref == 'refs/heads/master'
    environment: master_branch
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: inriavalda
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          tags: inriavalda/provsql:latest
